spring:
  application:
    name: LOAN-MANAGEMENT

  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loanserver
    username: postgres
    password: postgres
  
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
 
#server:
 # port: 8060